#index:
    #path: /
    #controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

home:
  path: /
  controller: App\Controller\HomeController::index

articles:
  path: /articles
  controller: App\Controller\HomeController::articles

article:
  path: /article/{id}
  controller: App\Controller\HomeController::article

fanArts:
  path: /fanArts
  controller: App\Controller\HomeController::fanArts

fanArt:
  path: /fanArt/{id}
  controller: App\Controller\HomeController::fanArt

admin_home:
  path: /admin/home
  controller: App\Controller\AdminController::homeAction

profile_home:
  path: /profile/home
  controller: App\Controller\HomeController::homeAction

admin_create_articles:
  path: /admin/articles/create
  controller: App\Controller\AdminController::createArticles

admin_update_articles:
  path: /admin/articles/update/{id}
  controller: App\Controller\AdminController::updateArticles

admin_create_fanArts:
  path: /admin/fanArts/create
  controller: App\Controller\AdminController::createFanArts

admin_update_fanArts:
  path: /admin/fanArts/update/{id}
  controller: App\Controller\AdminController::updateFanArts

admin_create_users:
  path: users/create
  controller: App\Controller\HomeController::createUsers

user_home:
  path: /user/home
  controller: App\Controller\HomeController::homeAction

user_create_articles:
  path: /user/articles/create
  controller: App\Controller\UserController::createArticles

user_update_articles:
  path: /user/articles/update
  controller: App\Controller\UserController::updateArticles

user_create_fanArts:
  path: /user/fanArts/create
  controller: App\Controller\UserController::createFanArts

user_update_fanArts:
  path: /user/fanArts/update
  controller: App\Controller\UserController::updateFanArts




